    protected static void verify(final Block block, final Error expectedError) {
        try {
            block.execute();
            if (expectedError != null) {
                fail("Expected validation to fail, but succeeded");
            }
        } catch (ClassificationException ex) {
            assertThat(ex.getError(), is(expectedError));
        }
    }

