    @Test(timeout=1000)
    public void testTaskThatThrowsException() throws Exception {
        
        AtomicInteger count = new AtomicInteger(0);
    
        Runnable thrower = new Runnable() {
            @Override
            public void run() {
                throw new RuntimeException("Intentionally failed for test purposes");

            }
        };
        
        Task throwerTask = m_coordinator.createTask(null, thrower);
        Task incrTask = m_coordinator.createTask(null, incr(count));
        
        incrTask.addPrerequisite(throwerTask);
        
        
        incrTask.schedule();
        throwerTask.schedule();
        
        
        incrTask.waitFor(1500, TimeUnit.MILLISECONDS);

        assertEquals(1, count.get());
    }

