    // NOTE: we retry server stop because of a concurrency issue inside Jetty that is not
    // easily solvable.
    public synchronized void stop() throws Exception {
        LogUtils.debugf(this, "shutting down jetty on port %d", m_config.port());
        try {
            m_server.stop();
        } catch (final InterruptedException e) {
            LogUtils.debugf(this, e, "Interrupted while attempting to shut down Jetty, propagating interrupt and trying again.");
            Thread.currentThread().interrupt();
            m_server.stop();
        } catch (final RuntimeException e) {
            LogUtils.debugf(this, e, "An exception occurred while attempting to shut down Jetty.");
            m_server.stop();
            throw e;
        }
    }

