    @Test 
    public void testNoClose() {
        try{ 
            out.connect(in);
            out.close();
         } catch (IOException IOE) {
             fail("The pipes are already connected or the pipe is already closed");
         } catch (NullPointerException NPE) {
             fail("The source being connected to is null");
         }
         try {
             out.connect(in);
         } catch (IOException IOE) {
             // Due to the fact that the pipe cannot be closed, it should throw this
             // from the multiple pipe connect attempts
         } catch (NullPointerException NPE) {
             fail("The source being connected to is null");
         }
    }

