    @Test
    public void testNullConnect() {
        
        try {
            out.connect(null);
            fail();
        } catch (NullPointerException e) {
            // If it gets to this point, then the exception must have been
            // thrown, and it is doing the right thing.
            return;
        } catch (IOException e) {
            fail(); // This should not happen
        }
        fail(); // If the exception was not caught, the code is not error checking properly
    }

