    public void setRequisition(final Requisition requisition) {
        m_requisition = requisition;
        try {
            requisition.validate();
        } catch (final ValidationException e) {
            if (m_throwable == null) {
                m_throwable = e;
            } else {
                LogUtils.debugf(this, e, "Requisition %s did not validate, but we'll ignore the exception because we've previously aborted with: %s", requisition, m_throwable);
            }
        }
    }

