	public void testWarnAssert() throws InterruptedException {
		LogUtils.infof(this, "An Info message");
		LogUtils.warnf(this, "A warn message");
 
		try {
			MockLogAppender.assertNotGreaterOrEqual(Level.WARN);
		} catch (final AssertionFailedError e) {
			return;
		}
		
		fail("Did not receive expected AssertionFailedError from MockLogAppender.assertNotGreatorOrEqual");
	}

